import Head from 'next/head'
import Home from '../components/pages/home'

export default function index() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />

    </div>
  )
}
